Replace miniblink example with minimal examples
Fraunhofer-AISEC/archie pull request #55
Opened 2023-01-14 15:35 UTC by ks0777

This PR replaces the miniblink example with minimal examples for the riscv and arm platform.

Each example consists of two endless loops. The fault configuration specifies faults for all three fault types which will break the first loop.

2023-02-10 20:17 UTC, lukasauer requested changes
Thank you for your contributions! This looks good overall, I just have a couple of comments I have included inline. In addition please change the following two things.

- Please squash the last two commits into the "add examples" commit.
- Please change the order of the commits so that the new examples are added before the miniblink example is removed.

2023-02-10 20:17 UTC, lukasauer commented on examples/riscv64/src/crt0.s
> +    .option push
The three `.option`s can be removed. This is only required when setting the `gp` register when linker relaxation is used.

2023-02-10 20:17 UTC, lukasauer commented on examples/riscv64/run.sh
> +python ../../controller.py --debug --fault fault.json  --qemu qemuconf.json output.hdf5
The shebang is missing, the same is the case for the stm32 version.

2023-02-10 20:17 UTC, lukasauer commented on examples/riscv64/qemuconf.json
> +	"additional_qemu_args" : "-bios none"
You can simply pass `none` using the `bios` qemuconf parameter.

2023-02-14 12:14 UTC, lukasauer approved these changes

2023-02-22 09:32 UTC, aewag approved these changes

2023-02-22 09:32 UTC, merged